version: "3"
services:
  my-app:
    build:
      context: .
      args:
        - NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY=${NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY}
    ports:
      - "2025:2025"
    environment:
      - STRIPE_SECRET_KEY=${STRIPE_SECRET_KEY}
